### ISSUE TITLE
Sem dados para 2019

### ISSUE THREAD

**Issue by johnnytardin** [dude333/rapina#10]
Parabéns pelo empenho, estou estudando quem sabe poder ajudar nesse projeto.

Na minha geração, para 2019 eu não vejo dados, é o esperado?

[√] Coletando dados ===========
[>] 2019 ---------------------
[ ] BPA já processado anteriormente
[ ] BPP já processado anteriormente
[ ] DRE já processado anteriormente
[x] ---- Sem dados para 2019
[>] 2018 ---------------------
[ ] BPA já processado anteriormente
[ ] BPP já processado anteriormente
[ ] DRE já processado anteriormente
[ ] DFC_MD já processado anteriormente
[ ] DFC_MI já processado anteriormente
[ ] DVA já processado anteriormente
[>] 2017 ---------------------

**Comment by johnnytardin** [comment]
Veriquei que é pq não tem na CVM =(

http://dados.cvm.gov.br/dados/CIA_ABERTA/DOC/DFP/DFC_MD/DADOS/

**Comment by dude333** [comment]
É isso mesmo :)
Agora no início de 2020 começam a ser publicados os relatórios de 2019 e em breve devem aparecer no site da CVM. 

Como cada empresa publica em um data diferente, é bom rodar o `rapina get` periodicamente até você conseguir os dados das empresas que necessita.
