### ISSUE TITLE
Relevância da linguagem GO perante outras como o Python

### ISSUE THREAD

**Issue by almirb** [dude333/rapina#14]
Boa tarde @dude333 !  

O que te levou a escolher desenvolver este pacote usando GO ao invés de linguagens mais populares, como o Python?  Só a título de curiosidade...

Parabéns pelo projeto! :)

**Comment by dude333** [comment]
Oi @almirb!

Eu achei a proposta dessa linguagem bem interessante. Ela tem uma sintaxe bem parecida com a da linguagem C (que eu já estava acostumado), mas com uma série de facilidades, como garbage collection e uma grande variedade de bibliotecas, como a que eu usei aqui para manipular arquivos Excel, por exemplo.

E por que não Python, que também tem essas mesmas facilidades? Porque com a liguagem Go você consegue compilar o mesmo código e criar executáveis para vários sistemas (Windows, Linux, Mac OS). E também para estudar melhor a linguagem. :)
