### ISSUE TITLE
Dados Resultados 1T20

### ISSUE THREAD

**Issue by jraiol** [dude333/rapina#16]
dude333, bom dia! 

Primeiramente, parabéns pelo excelente trabalho! É, de longe, a melhor ferramente de aquisição de dados aberta disponível no Brasil.

Uma dúvida de iniciante em relação ao script:

O último release (0.10.0) compila os dados até 2019, contudo, a maioria das empresas já divulgou os resultados do 1T20, e vejo que os dados são atualizados em tempo real na CVM (p.ex. http://dados.cvm.gov.br/dados/CIA_ABERTA/DOC/DFP/DRE/DADOS/ - dre_cia_aberta_2020.zip). Rodando o script com o comando get [-s], o cmd retorna erro em relação aos dados de 2020.

Você saberia me explicar o motivo? Só será possível acessar os balanços de 2020 em 2021?

Muito obrigado e parabéns novamente!
--

**Comment by dude333** [comment]
Oi @jraiol, bom dia!

Quando eu estava cursando matérias de finanças e contabilidade eu sentia falta de uma ferramenta que mostrasse os resultados financeiros de uma forma homogênea. Eu sei que existe esse formato no site da Bovespa, mas o site vive com problema, então resolvi coletar os dados da CVM. Mas trabalhar com aqueles arquivos csv não é nada prático, por isso criei o rapina.

Mas, claro, a ferramenta ajuda também nas análises das empresas quando se pensa em comprar suas ações. Como não era meu foco, não fiz o processamento dos dados trimestrais, mas já coloquei aqui na minha lista e, inclusive, a versão atual já está coletando os dados (só não aparece no relatório ainda).

Então, respondendo à sua pergunta, sim, na versão atual só teremos os dados de 2020 quando sair o relatório anual, ou seja, só em 2021. Mas assim que tiver um tempo vou implementar o relatório com os dados trimestrais.
