### ISSUE TITLE
Cálculo do CAPEX

### ISSUE THREAD

**Issue by andersongroto** [dude333/rapina#19]
Olá, bom dia!!

Inicialmente gostaria de agradecer pela publicação desta excelente ferramenta para análise de empresas!!

Não consigo calcular o CAPEX pelos dados fornecidos pelo arquivo gerado no report pois não encontrei os itens "Imobilizado" e "Intangível" dentro do item "Caixa Líquido de Atividades de Investimento", que normalmente apresenta código 6.02.

Gostaria de saber se existe a possibilidade de adicionar estas variáveis ao relatório para que possamos calcular o CAPEX

Agradeço desde já!!

**Comment by dude333** [comment]
Oi, bom dia!

O problema são os dados fornecidos pela CVM. Para o "Caixa Líquido de Atividades de Investimento" só é fornecido o total. Você pode conferir nos dados brutos usados para popular o banco de dados, como o `dfc_mi_cia_aberta_con_2019.csv`, por exemplo, no diretório `.data`:


CNPJ_CIA | DT_REFER | VERSAO | DENOM_CIA | CD_CVM | GRUPO_DFP | MOEDA | ESCALA_MOEDA | ORDEM_EXERC | DT_INI_EXERC | DT_FIM_EXERC | CD_CONTA | DS_CONTA | VL_CONTA
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
00.776.574/0001-56 | 31/12/2019 | 2 | B2W - COMPANHIA DIGITAL | 20990 | DF Consolidado - Demonstração do Fluxo de Caixa (Método Indireto) | REAL | MILHAR | ÚLTIMO | 01/01/2019 | 31/12/2019 | 6.01 | Caixa Líquido Atividades Operacionais | 157.938,00
00.776.574/0001-56 | 31/12/2019 | 2 | B2W - COMPANHIA DIGITAL | 20990 | DF Consolidado - Demonstração do Fluxo de Caixa (Método Indireto) | REAL | MILHAR | ÚLTIMO | 01/01/2019 | 31/12/2019 | 6.01.01 | Caixa Gerado nas Operações | 554.605,00
00.776.574/0001-56 | 31/12/2019 | 2 | B2W - COMPANHIA DIGITAL | 20990 | DF Consolidado - Demonstração do Fluxo de Caixa (Método Indireto) | REAL | MILHAR | ÚLTIMO | 01/01/2019 | 31/12/2019 | 6.01.02 | Variações nos Ativos e Passivos | -385.476,00
00.776.574/0001-56 | 31/12/2019 | 2 | B2W - COMPANHIA DIGITAL | 20990 | DF Consolidado - Demonstração do Fluxo de Caixa (Método Indireto) | REAL | MILHAR | ÚLTIMO | 01/01/2019 | 31/12/2019 | 6.01.03 | Outros | -11.191,00
00.776.574/0001-56 | 31/12/2019 | 2 | B2W - COMPANHIA DIGITAL | 20990 | DF Consolidado - Demonstração do Fluxo de Caixa (Método Indireto) | REAL | MILHAR | ÚLTIMO | 01/01/2019 | 31/12/2019 | 6.02 | Caixa Líquido Atividades de Investimento | -1.723.688,00
00.776.574/0001-56 | 31/12/2019 | 2 | B2W - COMPANHIA DIGITAL | 20990 | DF Consolidado - Demonstração do Fluxo de Caixa (Método Indireto) | REAL | MILHAR | ÚLTIMO | 01/01/2019 | 31/12/2019 | 6.03 | Caixa Líquido Atividades de Financiamento | 1.981.609,00
00.776.574/0001-56 | 31/12/2019 | 2 | B2W - COMPANHIA DIGITAL | 20990 | DF Consolidado - Demonstração do Fluxo de Caixa (Método Indireto) | REAL | MILHAR | ÚLTIMO | 01/01/2019 | 31/12/2019 | 6.04 | Variação Cambial s/ Caixa e Equivalentes | 0,00
00.776.574/0001-56 | 31/12/2019 | 2 | B2W - COMPANHIA DIGITAL | 20990 | DF Consolidado - Demonstração do Fluxo de Caixa (Método Indireto) | REAL | MILHAR | ÚLTIMO | 01/01/2019 | 31/12/2019 | 6.05 | Aumento (Redução) de Caixa e Equivalentes | 415.859,00
00.776.574/0001-56 | 31/12/2019 | 2 | B2W - COMPANHIA DIGITAL | 20990 | DF Consolidado - Demonstração do Fluxo de Caixa (Método Indireto) | REAL | MILHAR | ÚLTIMO | 01/01/2019 | 31/12/2019 | 6.05.01 | Saldo Inicial de Caixa e Equivalentes | 3.119.948,00
00.776.574/0001-56 | 31/12/2019 | 2 | B2W - COMPANHIA DIGITAL | 20990 | DF Consolidado - Demonstração do Fluxo de Caixa (Método Indireto) | REAL | MILHAR | ÚLTIMO | 01/01/2019 | 31/12/2019 | 6.05.02 | Saldo Final de Caixa e Equivalentes | 3.535.807,00

**Comment by andersongroto** [comment]
Boa tarde!!

Obrigado pela resposta! Como você consegue esses dados da CVM?

**Comment by dude333** [comment]
Eu pego deste endereço para os dados anuais:

http://dados.cvm.gov.br/dados/CIA_ABERTA/DOC/DFP/

E este para os trimestrais:

http://dados.cvm.gov.br/dados/CIA_ABERTA/DOC/ITR/DADOS/

E jogo todos esses dados numa base de dados SQLite (`.data/rapina.db`).

**Comment by andersongroto** [comment]
Entendi!
Obrigado dude333!!
