### ISSUE TITLE
Versão para OSX

### ISSUE THREAD

**Issue by Imparium** [dude333/rapina#2]
Baixei na release o arquivo rapina, mas quando tento executar aparece: "rapina: rapina: cannot execute binary file"

**Comment by acdesouza** [comment]
Eu instalei o Go pelo Homebrew e consegui seguir o [passo-a-passo para compilação](https://github.com/dude333/rapina#3-como-compilar):

```
$ brew install go
$ cd rapina/cli
$ make
$ ./rapina get
```

**Comment by dude333** [comment]
@Imparium, eu compilei e joguei 2 arquivos para o OSX. Basta escolher a versão, provavelmente a rapina-darwin-10.6-amd64, renomear para rapina e alterar o modo de execução: `chmod +x rapina`.

**Comment by dude333** [comment]
Acho que dessa vez compilei corretamente. Fiz upload do `rapina-osx` nos arquivos do release 0.5. Avise-me se funcionou.

**Comment by walterpitman** [comment]
Bom dia. Versão do Macos nao gera os reports completos. Apenas utiliza o arquivo "DVA" sem utilizar os outros.

**Comment by dude333** [comment]
@walterpitman, você pode passar o conteúdo da pasta **.data** (`ls -l`)?

Segue como está aqui, para comparação:

```
  6983017 Feb 08 00:39 bpa_cia_aberta_con_2013.csv
  6830432 Feb 08 00:38 bpa_cia_aberta_con_2014.csv
  6747590 Feb 08 00:37 bpa_cia_aberta_con_2015.csv
  6752094 Feb 08 00:37 bpa_cia_aberta_con_2016.csv
  6754404 Feb 08 00:36 bpa_cia_aberta_con_2017.csv
  6405176 Feb 08 00:36 bpa_cia_aberta_con_2018.csv
 12783136 Feb 08 00:39 bpp_cia_aberta_con_2013.csv
 12500851 Feb 08 00:38 bpp_cia_aberta_con_2014.csv
 12351857 Feb 08 00:37 bpp_cia_aberta_con_2015.csv
 12357197 Feb 08 00:37 bpp_cia_aberta_con_2016.csv
 12354116 Feb 08 00:36 bpp_cia_aberta_con_2017.csv
 12604426 Feb 08 00:36 bpp_cia_aberta_con_2018.csv
      512 Feb 08 00:41 cache
    26015 Feb 08 00:39 dfc_md_cia_aberta_con_2013.csv
    25691 Feb 08 00:39 dfc_md_cia_aberta_con_2014.csv
    27293 Feb 08 00:38 dfc_md_cia_aberta_con_2015.csv
    25712 Feb 08 00:37 dfc_md_cia_aberta_con_2016.csv
    22756 Feb 08 00:36 dfc_md_cia_aberta_con_2017.csv
    22762 Feb 08 00:36 dfc_md_cia_aberta_con_2018.csv
  1547696 Feb 08 00:39 dfc_mi_cia_aberta_con_2013.csv
  1514457 Feb 08 00:39 dfc_mi_cia_aberta_con_2014.csv
  1487024 Feb 08 00:38 dfc_mi_cia_aberta_con_2015.csv
  1486682 Feb 08 00:37 dfc_mi_cia_aberta_con_2016.csv
  1498690 Feb 08 00:36 dfc_mi_cia_aberta_con_2017.csv
  1516291 Feb 08 00:36 dfc_mi_cia_aberta_con_2018.csv
  3637501 Feb 08 00:39 dre_cia_aberta_con_2013.csv
  3563460 Feb 08 00:38 dre_cia_aberta_con_2014.csv
  3520533 Feb 08 00:38 dre_cia_aberta_con_2015.csv
  3515729 Feb 08 00:37 dre_cia_aberta_con_2016.csv
  3534533 Feb 08 00:36 dre_cia_aberta_con_2017.csv
  3567761 Feb 08 00:36 dre_cia_aberta_con_2018.csv
  5597098 Feb 08 00:39 dva_cia_aberta_con_2013.csv
  5494481 Feb 08 00:39 dva_cia_aberta_con_2014.csv
  5421939 Feb 08 00:38 dva_cia_aberta_con_2015.csv
  5406084 Feb 08 00:37 dva_cia_aberta_con_2016.csv
  5433045 Feb 08 00:36 dva_cia_aberta_con_2017.csv
  5500551 Feb 08 00:36 dva_cia_aberta_con_2018.csv
278437888 Feb 08 00:41 rapina.db
```

(Eu testei no Linux e Windows.)

**Comment by dude333** [comment]
Oi @walterpitman, descobri o problema aqui. Era um bug que foi sanado no commit 9642302efc0d730587d113fad0f85f7d74978bd0.

Eu notei que as empresas eventualmente mandam retificações dos seus balanços à CVM, então o programa precisa apagar os dados do ano a ser importado antes de inseri-los novamente no banco de dados, mas estava apagando dados a mais. 

O problema não está relacionado ao macOS, mas se puder testar o fix eu agradeço.

**Comment by walterpitman** [comment]
Desculpa a demora!

Testei!! tudo certo ! agora o report está completo com todos os arquivos!!

**Comment by walterpitman** [comment]
Não sei se é bug. mas o arquivo setores.yml fica em branco. não está sendo puxado as informações do site da B3
