### ISSUE TITLE
Problemas em abrir o programa

### ISSUE THREAD

**Issue by LucasFunayama** [dude333/rapina#20]
Sou leigo na parte de computação como um todo, ao abrir o programa arrastando-o para o cmd recebo o seguinte comunicado:

Rapina - Dados Financeiros de Empresas Brasileiras - v0.11.0-2020-05-29
(2018-2020) github.com/dude333/rapina

Este  programa  coleta  informações sobre os dados financeiros  do
site da CVM e os exporta para uma planilha. Dados usados:  balanço
patrimonial ativo e passivo, e também o demonstrativo de resultado
do exercício (DRE).

Uso:
  rapina [command]

Comandos Disponíveis:
  get         Baixa os arquivos da CVM e os armazena no bando de dados
  help        Help about any command
  list        Lista informações armazenadas no banco de dados
  report      Cria planilha com dados da companhia escolhida

Flags:
  -h, --help     help for rapina
  -t, --toggle   Help message for toggle

Use "rapina [command] --help" para mais informações sobre um comando.
--------------------------------------------------------------------------------------------------------------------------------------------
Porém depois que tento executar os comandos listados abaixo, recebo: 
'/rapina' is not recognized as an internal or external command,
operable program or batch file.
--------------------------------------------------------------------------------------------------------------------------------------------
Poderia me ajudar?

**Comment by andremsilveira** [comment]
Agradeço a ajuda, pois estou tendo o mesmo problema.

**Comment by dude333** [comment]
Vocês precisam acessar a pasta onde está o arquivo usando o cmd.

Por exemplo:

```
Microsoft Windows [Version 10.0.16299.1932]
(c) 2017 Microsoft Corporation. All rights reserved.

C:\Users\dude333>cd Downloads

C:\Users\dude333\Downloads>rapina get
```

Vocês precisam rodar primeiro o `rapina get` para coletar todos os dados. Quando terminar, aí sim podem criar o relatório. Para a Weg, por exemplo: `rapina report weg`, e a planilha da Weg será criada dentro do diretório `reports`.

**Comment by LucasFunayama** [comment]
Muito obrigado mestre, consegui rodar o programa sem problemas!!

Deixa eu te fazer mais algumas perguntas, os comandos , -l, -s funcionam, no meu apenas o -e,-h está funcionando. Teria como pegar esses dados do trimestre ou apenas do ano, desde já agradeço!!!! Muito bem desenvolvido, meus parabéns!!

**Comment by dude333** [comment]
Oi Lucas, eu até salvo os dados trimestrais, mas eu uso esses dados para apresentar os valores do ano atual, somando os últimos 4 trimestres para se ter uma mesma base de comparação com os anos anteriores.

Eu desenvolvi este programa usando a linguagem Go (https://golang.org/).

**Comment by gustavomoers** [comment]
olá, também sou leigo em computação, e não to conseguido executar o programa em windows, executei o recomendado acima e recebi a seguinte mensagem:

C:\Users\Gustavo\Downloads>rapina get
'rapina' não é reconhecido como um comando interno
ou externo, um programa operável ou um arquivo em lotes.

Eu verifiquei se o executável estava na pasta Downloads, e realmente estava, sabe me dizer qual pode ser o problema?
