### ISSUE TITLE
Arquivo ITR

### ISSUE THREAD

**Issue by EFNinvest** [dude333/rapina#21]
Olá, boa noite, primeiramente obrigado pelo programa, muito funcional,

Eu particurlamente não estou conseguindo baixar os arquivos ITR de 2020, pelo comando rapina GET, o erro é "Erro ao processar arquivo: arquivo  não encontrado"

Gostaria de saber se o problema é só comigo ou com mais alguém.

Mais uma vez, obrigado 01/07/2020

**Comment by dude333** [comment]
Oi @EFNinvest,

Descobri o problema, que só aparecia no Windows, e arrumei no commit 9cf8f59 e joguei o executável no [release v0.11.1](https://github.com/dude333/rapina/releases/tag/v0.11.1).

**Comment by EFNinvest** [comment]
Olá @dude333 ,

Por aqui tambem parece que esta tudo certo, obrigado.
