### ISSUE TITLE
Problema com DRE trimestral

### ISSUE THREAD

**Issue by EFNinvest** [dude333/rapina#25]
Olá bom dia, o programa está com problema no calculo da TTM DRE dos dados trimestrais, ele está somando os dois primeiros trimestres do ano 2019 com os dois primeiros trimestres do ano 2020, o certo seria a soma dos dois ultimos trimesre do ano 2019 com os dois primeiros trimestres do ano 2020.
Acredito que o fluxo de caixa e valor adicionado contenham o mesmo erro, obrigado

**Comment by dude333** [comment]
O ITR está sendo apresentado com os valores do trimestre e acumulado do ano. 

Exemplo:
DT_INI_EXERC | DT_FIM_EXERC | CD_CONTA | DS_CONTA
-- | -- | -- | --
01/01/2019 | 31/03/2019 | 3.01 | Receita de Venda de Bens e/ou Serviços
01/01/2019 | 30/06/2019 | 3.01 | Receita de Venda de Bens e/ou Serviços
01/04/2019 | 30/06/2019 | 3.01 | Receita de Venda de Bens e/ou Serviços
01/01/2020 | 31/03/2020 | 3.01 | Receita de Venda de Bens e/ou Serviços
01/01/2020 | 30/06/2020 | 3.01 | Receita de Venda de Bens e/ou Serviços
01/04/2020 | 30/06/2020 | 3.01 | Receita de Venda de Bens e/ou Serviços

**Fix:** incluir no cáculo apenas os dados do trimestre:

https://github.com/dude333/rapina/blob/9534787d662daac66a4cf42792db6e0bcf2dabb8/reports/db.go#L240

**Comment by dude333** [comment]
Fix: 57293037e9d3f781f581423eaeb1f5f794bcd070

Os dados dos arquivos ITR contém informações trimestrais e/ou semestrais. Ainda não encontrei um jeito de lidar com isso, então só estou considerando agora os dados trimestrais para o cálculo do TTM.

Fiz alguns testes e parece que está ok, mas muitos dos dados estão vindo zerados, como a depreciação e fluxo de caixa.

Se achar algum problema nos testes, me avise. Um dos dados que acaba ficando errado pelo fato de não conseguir o valor de TTM da depreciação é o EBITDA.

**Comment by dude333** [comment]
Fix: ed842560602bf864838e51bea8c4aa091bfbff3c

Não sei se arrumaram isso nos dados da CVM, mas consegui agora mostrar os resultados corretos do TTM (havia também um erro na balanço). Agora estou usando como base para o último ano a data armazenada no banco de dados por empresa.

Conferi o resultado de várias empresas e aparentemente está ok agora. Vou continuar observando os valores conforme os próximos resultados forem publicados.
