### ISSUE TITLE
Excelente Projeto! Gostaria de contribuir

### ISSUE THREAD

**Issue by robson-jardim** [dude333/rapina#27]
Boa noite Dude,

Estava escrevendo um projeto para executar as mesmas atividades! Foi um grande supresa encontrar o seu projeto.

Como eu poderia contribuir para o projeto? Tem um roadmap? 

Gostaria de marcar um bate-papo?

Abs,

**Comment by dude333** [comment]
Oi @robson-jardim, seja bem-vindo. Você pode fazer um fork do projeto e propor umas melhorias via *pull request*.

Não montei nenhum roadmap, mas estou com problema para definir os dados do TTM (acumulado dos últimos 12 meses). Alguns valores são apresentados no acumulado do trimestre, outros no acumulado semestral. 

O que fiz por hora para contornar o problema foi ignorar os dados semestrais, pois há dados que são apresentados no formato trimestral e semestral, então fica difícil distinguir qual dado deveria ser usado.

Outro ponto seria tratar os dados individuais. Eu trato apenas os arquivos consolidados, mas há algumas empresas que não possuem controladoras e, portanto, o dado só sai no arquivo individual. Precisaria verificar quais são essas empresas parar incluí-las no banco de dados.

Mas fique a vontade para perguntar o que quiser sobre a estrutura do programa.

Abs.!!
