### ISSUE TITLE
Problema na operação do executável

### ISSUE THREAD

**Issue by lyto1** [dude333/rapina#29]
Olá, estou passando pelo mesmo problema reportado por alguns usuários antes ao não conseguir abrir o executável. 

Estou usando o Windows 10 e apesar de abrir o cmd na pasta onde o executável está, não consigo executar os comandos. O erro apontado é o seguinte: 'rapina' não é reconhecido como um comando interno ou externo, um programa operável ou um arquivo em lotes.

Tem alguma resolução? Desde já agradeço.

**Comment by dude333** [comment]
Oi @lyto1, você está usando este executável?

https://github.com/dude333/rapina/releases/download/v0.12.2/rapina-0.12.2-windows-4.0-amd64.exe

**Comment by lyto1** [comment]
Esse mesmo. Até fiz um novo download mas não resolveu, permanece o mesmo erro.

**Comment by dude333** [comment]
O que eu reparei aqui, usando o Firefox, é que ele cria 2 arquivos:

```
23/02/2021  23:14                 0 rapina-0.12.2-windows-4.0-amd64.exe
23/02/2021  23:14         6.848.000 rapina-0.12.2-windows-4.0-amd64.exe.part
```

E só após clicar em "Abrir" no Firefox e dar um OK confirmando ao Windows para executar o arquivo é que o .exe.part é copiado para o .exe.

**Comment by johnnytardin** [comment]
O download não foi finalizado.
Repare que o tamanho do exe é zero.

Tente tentar fazer o download novamente, ou teste com outro browser.

Se tiver algum problema ainda com a exucução, esse vídeo abaixo tem algumas instruções.
https://www.youtube.com/watch?v=yVzFluJ1NMQ

**Comment by lyto1** [comment]
Não tive esse problema ao baixar o executável, mas de qualquer forma o erro permanece. É como se faltasse algo no Windows pra poder executar, mas não consigo identificar o que é.

**Comment by dude333** [comment]
O programa não usa nenhuma biblioteca externa.

Eu compilei uma nova versão, tente rodá-lo na versão 32-bits:

https://github.com/dude333/rapina/releases/download/v0.13.0/rapina-0.13.0-windows-4.0-386.exe

**Comment by lyto1** [comment]
Oi @dude333, nenhuma novidade. Formatei o Windows tem pouco tempo, por isso imaginei que faltasse algo com ele, mas pelo jeito não. De qualquer forma, agradeço pela ajuda.

**Comment by gustavomoers** [comment]
por aqui estou com o mesmo problema

**Comment by gustavomoers** [comment]
tentei realizar as ações do video acima, tentei instalar a versão 32-bits, tentei instalar por outro browse, mas continuo tendo a mesma resposta:  'rapina' não é reconhecido como um comando interno ou externo, um programa operável ou um arquivo em lotes.  Alguém encontrou uma solução?

**Comment by dude333** [comment]
@lyto1 e @gustavomoers, uma possibilidade é vocês estarem tentando rodar o programa a partir do diretório errado. A config default dos browsers é salvar os arquivos na pasta `Downloads`, mas o diretório default ao abrir o `cmd` é o C:\user\\_seunome_.

Tente mudar para o diretório Downloads: `cd Downloads` ou `cd \user\seunome\Downloads`, só tome o cuidado de trocar _seunome_ pelo nome que o Windows deu para o seu diretório. 

Ou então, use o comando `cd %userprofile%\Downloads` que o Windows vai substituir o %userprofile% pelo diretório correto.

Sugiro, após o teste, mudar o rapina.exe para um outro diretório.

**Comment by lyto1** [comment]
Tomei esse cuidado desde o princípio. Criei uma pasta exclusiva para o programa e sempre abro o cmd por ela.

**Comment by dude333** [comment]
@lyto1, tem como você jogar aqui a saída dos comandos abaixo?

    cd

depois

    dir rapina*.*

e, finalmente (usar o nome do executável que você colocou no diretório):

    rapina-0.13.0-windows-4.0-386.exe

**Comment by dude333** [comment]
Usei o github actions para compilar esta última versão. Vale a pena testar para ver se funciona:

* [Versão Windows 32-bits](https://github.com/dude333/rapina/releases/download/v0.13.1/rapina-v0.13.1-windows-4.0-386.exe)
* [Versão Windows 64-bits](https://github.com/dude333/rapina/releases/download/v0.13.1/rapina-v0.13.1-windows-4.0-amd64.exe)

**Comment by lyto1** [comment]
As saídas foram:
`cd` 
`C:\rapina`

`C:\rapina>dir rapina*-*`
 ```
O volume na unidade C não tem nome.
 O Número de Série do Volume é B007-5968

 Pasta de C:\rapina

25/03/2021  19:43         6.206.464 rapina-v0.13.1-windows-4.0-386.exe
               1 arquivo(s)      6.206.464 bytes
               0 pasta(s)   153.790.259.200 bytes disponíveis
```
`C:\rapina>rapina-v0.13.1-windows-4.0-386.exe`
```
Rapina - Dados Financeiros de Empresas Brasileiras - v0.13.1-2021-03-24
(2018-2020) github.com/dude333/rapina


Este  programa  coleta  informações sobre os dados financeiros  do
site da CVM e os exporta para uma planilha. Dados usados:  balanço
patrimonial ativo e passivo, e também o demonstrativo de resultado
do exercício (DRE).

Uso:
  rapina [command]

Comandos Disponíveis:
  get         Baixa os arquivos da CVM e os armazena no bando de dados
  help        Help about any command
  list        Lista informações armazenadas no banco de dados
  report      Cria planilha com dados da companhia escolhida

Flags:
  -h, --help     help for rapina
  -t, --toggle   Help message for toggle

Use "rapina [command] --help" para mais informações sobre um comando.
```
`C:\rapina>rapina get`
```
'rapina' não é reconhecido como um comando interno
ou externo, um programa operável ou um arquivo em lotes.
```

**Comment by dude333** [comment]
Você precisa ou renomear o `rapina-v0.13.1-windows-4.0-386.exe` para `rapina.exe`, ou rodar:

    rapina-v0.13.1-windows-4.0-386.exe get

:)

**Comment by lyto1** [comment]
Deu certinho! Muito obrigado e parabéns pelo trabalho @dude333! :D
