### ISSUE TITLE
Parabens pelo projeto!Animal!

### ISSUE THREAD

**Issue by PedroDnT** [dude333/rapina#34]
Vou estudar o código e pensar no que ajudar... Tem algum ponto mais urgente que precisa de ajuda? Trabalho co research/valuation, pensei em adicionar algo do tipo o que acha? 

Abs!

**Comment by dude333** [comment]
Opa, ajuda é sempre bem vinda. No momento estou incluindo o P/L no relatório. Mas a quantidade de ações e os preços estão sem os ajustes dos desdobramentos. Veja o exemplo da Weg:

## WEG
![image](https://user-images.githubusercontent.com/2881040/118640786-c5c34280-b7af-11eb-99a1-6e9fb836aa02.png)

Você sabe onde consigo uma lista com o histórico de desdobramentos/grupamentos? De preferência da B3 ou CVM.

Valeu!

**Comment by PedroDnT** [comment]
Cara acho que consigo pegar da bloomberg, vou ver amanha.
