### ISSUE TITLE
Problema de codificação no .xlsx

### ISSUE THREAD

**Issue by gusttav-lang** [dude333/rapina#35]
Mano parabéns pelo projeto! Estava querendo começar algo parecido e encontrei seu projeto. Estou tentando abrir o report .xlsx das empresas no Python, porém não consigo devido a algum problema de codificação do arquivo. É possível corrigir isso abrindo o arquivo no excel e salvando novamente, porém é inviável fazer isso para mais de 400 arquivos. Alguma ideia de como resolver?

Eu não conheço Go, por isso até considerei abrir o BD diretamente no Python. Estou estudando NextJS e pretendo criar um servidor web com essas informações. Se tiver alguma sugestão estou aberto para implementar.

Abraços!

**Comment by dude333** [comment]
Po, legal que você gostou. Eu até comecei alguma coisa aqui usando um servidor web local para as informações de FII. Vou fazer para as ações também no futuro (tem que compilar a última versão e rodar como `rapina server` e depois abrir o browser em http://localhost:3000).

Para a criação dos xlsx eu uso essa biblioteca [github.com/360EntSecGroup-Skylar/excelize](https://github.com/360EntSecGroup-Skylar/excelize), na versão 1.4.1. Eles já estão na 2.4.1. Quando tiver um tempo vou tentar trocar e aí te aviso para poder testar.

**Comment by dude333** [comment]
Se você ainda estiver com problema para abrir o xlsx, tente verificar se funciona na versão 2: https://github.com/dude333/rapinav2

É um repositório temporário até eu migrar para este aqui.
