### ISSUE TITLE
Possibilitar geração de relatório em stdout

### ISSUE THREAD

**Issue by zamariola** [dude333/rapina#39]
**Contexto**
Atualmente os relatórios de DFP e ITR são gerados em excel, seria interessante possibilitar a geração destes diretamente no stdout como está sendo feito com FII.  

**Objetivo**
O objetivo desta feature é permitir que se use ferramentas de Unix+Terminal+Software de Terceiros para analisar os dados gerados, permitindo que o rapina se torne uma base de armazenamento e ponto de partida para data science dos dados financeiros.

**Comportamentos esperados**

Espera-se que a execução de um comando `report` com -format=stdout gere os relatórios da companhia via stdout. O relátorio esperado é apenas de dados brutos (contas numeradas) sem apresentar as análises verticais ou horizontais e o P&L que está ao final do excel.
Para facilitar a manipulação, converter dados que estão em formato coluna (período anual) para formato linha adicionando colunas adicionais. Por exemplo:

Relatório presente no Excel:

AZUL S.A. | -- | [2016] | [2017]
-- | -- | -- | --
1 | Ativo Total | 8,400 | 10,317
1.01 | Ativo Circulante | 1,910 | 3,304
1.01.01 | Caixa e Equivalentes de Caixa | 549 | 762

Seria convertido para 

AZUL S.A. | -- | -- | --
-- | -- | -- | --
2016 | 1 | Ativo Total | 8,400
2016 | 1.01 | Ativo Circulante | 1,910
2016 | 1.01.01 | Caixa e Equivalentes de Caixa | 549
2017 | 1 | Ativo Total | 10,317
2017 | 1.01 | Ativo Circulante | 3,304
2017 | 1.01.01 | Caixa e Equivalentes de Caixa | 762

**Condições para validação**

1) Executar `./rapina report -format=stdout azul`
2) Verificar a geração de relátorio no stdout relativo a companhia especificada

**Comment by zamariola** [comment]
Estou trabalhando nessa feature no meu fork, em breve abro um PR

**Comment by dude333** [comment]
Oi @zamariola, muito obrigado pela contribuição!! Estava super enrolado em um projeto e acabei não conseguindo dar atenção aqui. Já vou fazer aqui o merge do seu PR.
