### ISSUE TITLE
Como acessar o DRA?

### ISSUE THREAD

**Issue by vdurante** [dude333/rapina#7]
Tudo bem? Parabéns pela aplicação! Pode me dizer se os arquivos da CVM disponibilizam o DRA, ou se eles são resultados de algum cálculo? Estou meio perdido. Obrigado!

**Comment by dude333** [comment]
Opa, tudo bem e obrigado!! Espero que esteja tudo bem por aí também.

Você quis dizer DRA ou DRE (demonstração do resultado do exercício)? 

Eu uso os seguintes arquivos: 
_bpa_cia_aberta_con_2018.csv_ - balanço patrimonial dos ativos
_bpp_cia_aberta_con_2018.csv_  - balanço patrimonial dos pasivos
_dre_cia_aberta_con_2018.csv_ - demonstração do resultado do exercício
_dfc_mi_cia_aberta_con_2018.csv_ - demonstração do fluxo de caixa
_dva_cia_aberta_con_2018.csv_ - demonstração de valor adicionado

(Esse _con_ no nome do arquivo é de consolidado.)

Estão todos localizados neste endereço:
http://dados.cvm.gov.br/dados/CIA_ABERTA/DOC/DFP/
