### ISSUE TITLE
Indicadores fundamentalistas

### ISSUE THREAD

**Issue by walterpitman** [dude333/rapina#9]
primeiramente parabens pelo codigo. 
eu tenho alguns indicadores que gosto de usar porem nao encontro eles normalmente nos sites habituais.

se tiver como,
como eu faço pra ajudar a colocar estes indicadores na planilha de excel?  e tambem o valuation da empresa?

obrigado

**Comment by dude333** [comment]
Opa, obrigado!

Dependendo de quais indicadores, talvez possam ser implementados dentro da função [metricsList](https://github.com/dude333/rapina/blob/66aeb609b4fdff2a2d1484f41b39748b40a91a07/reports/reports.go#L482).

Você tem alguns exemplos de quais indicadores você usa?

**Comment by walterpitman** [comment]
este site do damodaran mostra indicadores http://pages.stern.nyu.edu/~adamodar/New_Home_Page/datafile/variable.htm
bem interessante pra comecar dentre eles tem o ciclo financeiro da empresa 
Capital de giro (cdg):                                 Pass N circ + Patr Liq - Ativ N Circ
Necessidade de capital de giro  (ncg):    (Ativo Circulante - caixa ) - (Pass circulante - dividendos - emprestimo)
Saldo de tesouraria: CDG - NCG
sou zerado em programação mas queria ajudar de alguma forma.

outra coisa interessante era computar em planilha todos os indicadores das empresas de cada ano. tipo pra fazer um filtro comparativo. igual tem o site fundamentus, porém só tem la dados mais recentes.

o Capex vejo que nao aparece, pq o fluxo de caixa de investimento nao esta separado. so aparece o total. sabe como poderiamos pegar esta informação?
neste site https://www.rad.cvm.gov.br/ENET/frmGerenciaPaginaFRE.aspx?NumeroSequencialDocumento=80947&CodigoTipoInstituicao=1
aparece detalhado o fluxo de caixa.

**Comment by walterpitman** [comment]
Bom dia!
Se quiser também me passar a literatura da programaçao para eu entender. ai posso colaborar se precisar!

abraço

**Comment by dude333** [comment]
Opa, seria uma boa, pois estou sem tempo ultimamente. Eu até estava vendo de como usar a evolução das contas no modelo dinâmico do fleuriet, quem sabe no futuro :)

Eu usei a linguagem Go, você pode começar a estudar por aqui:

https://go-tour-br.appspot.com

Abs.

**Comment by dude333** [comment]
Oi @walterpitman, eu incluí alguns indicadores extras mais os que você passou (que acredito serem o modelo de Fleuriet) no commit c80ed4d69fee47e9fc6b1342a507598affb8b337.

Eu tentei achar, sem sucesso, os detalhes destas fórmulas que você passou:

```
Capital de giro (cdg): Pass N circ + Patr Liq - Ativ N Circ
Necessidade de capital de giro (ncg): (Ativo Circulante - caixa ) - (Pass circulante - dividendos - emprestimo)
Saldo de tesouraria: CDG - NCG
```

Geralmente o capital de giro é calculado subtraindo o PassCirc do AtivoCirc, mas eu deixei no relatório a fórmula que você passou.

Seguem alguns exemplos e agradeço se puder conferi-los.

### Engie:


  | [2009] | [2010] | [2011] | [2012] | [2013] | [2014] | [2015] | [2016] | [2017] | [2018] | [2019] | [2020]
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
Capital de Giro (CDG) | 466 | (353) | 54 | 295 | 155 | 1.331 | 1.454 | 1.554 | (1.941) | 386 | 766 | 2.352
Necessidade de Capital de Giro   (NCG) | 3.056 | 3.453 | 4.096 | 3.919 | 3.656 | 4.331 | 3.825 | 3.883 | 4.461 | 8.914 | 13.502 | 16.419
Saldo de Tesouraria (T) | (2.590) | (3.806) | (4.043) | (3.625) | (3.502) | (3.000) | (2.371) | (2.328) | (6.402) | (8.527) | (12.736) | (14.067)

### WEG:


  | [2009] | [2010] | [2011] | [2012] | [2013] | [2014] | [2015] | [2016] | [2017] | [2018] | [2019] | [2020]
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
Capital de Giro (CDG) | 2.275 | 2.855 | 3.114 | 2.697 | 4.274 | 4.717 | 6.094 | 5.849 | 5.089 | 4.405 | 5.270 | 6.674
Necessidade de Capital de Giro   (NCG) | 4.314 | 5.388 | 6.659 | 3.270 | 4.293 | 5.774 | 8.235 | 7.020 | 6.201 | 6.318 | 6.148 | 5.467
Saldo de Tesouraria (T) | (2.040) | (2.533) | (3.545) | (573) | (19) | (1.057) | (2.140) | (1.171) | (1.112) | (1.913) | (878) | 1.207

**Comment by walterpitman** [comment]
oi @dude333 
"Geralmente o capital de giro é calculado subtraindo o PassCirc do AtivoCirc, mas eu deixei no relatório a fórmula que você passou"
sim! Ativo circulante - passivo circulante irá dar o mesmo resultado. pode fazer nele se ficar mais fácil.

fiz um report da weg no app rapina e nao achei as métricas Fleuriet

mas vou te colocar aqui o número das contas do balanço patrimonial

**Saldo de tesouraria: 
(1.01.01 | Caixa e Equivalentes de Caixa + 1.01.02 | Aplicações   Financeiras ) - ( 2.01.04 | Empréstimos e Financiamentos + 2.01.05.02.01 | Dividendos e JCP   a Pagar + 2.01.05.02.02 | Dividendo Mínimo   Obrigatório a Pagar )

Capital de giro:
(1.01 | Ativo Circulante) - (2.01 | Passivo Circulante)**

**NCG: CG - ST**

Acho que dessa forma fica mais fácil


Me diga o que acha!!? grande abraço

**Comment by walterpitman** [comment]
segue exemplo da Weg


ST     | 1.194 | 1.471 | 1.227 | 838 | 2.373 | 2.615 | 2.978 | 3.581 | 2.398 | 1.315 | 2.309 | 3.707
CDG | 2.275 | 2.855 | 3.114 | 2.697 | 4.274 | 4.717 | 6.094 | 5.849 | 5.089 | 4.405 | 5.270 | 6.674
NCG | 1.080 | 1.385 | 1.887 | 1.859 | 1.900 | 2.103 | 3.117 | 2.267 | 2.691 | 3.089 | 2.961 | 2.967

Mostrando inclusive muito mais saúde financeira
acho que com as métricas que te passei.

os cálculos ficarão tops!!!

**Comment by dude333** [comment]
Opa, legal. Ainda vou conferir se esses itens aparecem em todas as empresas (geralmente o código acaba mudando em alguns casos).

Para mostrar as métricas de Fleuriet que eu fiz até o momento é necessário passar o flag `-F`. Ou pode passar o `--all` para mostrar todas as métricas:

    ./rapina report -all weg

Mas para isso você precisa compilar o último commit (a versão que está na aba de releases não tem essa função ainda).

Depois quero ver se faço um relatório com as métricas de todas as empresas.

**Comment by walterpitman** [comment]
@dude333 concordo. Até me assustei. Parece que o arquivo da cvm ficou mais completo. O fluxo de caixa está totalmente dividido. Aparece até o capex agora. Vou ver se é pra todas também. Acho que é melhoria dos dados abertos mesmo. Tomara.

Vou tentar achar esse commit. Mas nem sei o que é. Kkkkkk. Tenho tanta ideia. Pena que não manjo de programação. 

Projeto espetacular este. Vamos pro próximo nível!

**Comment by walterpitman** [comment]
@dude333 uma pergunta.

vi que está adicionado o numero de shares por ano na empresa.

será que teriamos como ter o valor de mercado do fechamento do ano em 31/12 e junto com a maxima e minima daquele ano? e discriminado em cada ano?

porque daí dá pra calcular entrerprise value... e fora outras métricas que dependem disso. 
p/l , Ev/ebit e por ai vai...

obrigado

**Comment by dude333** [comment]
Estou vendo aqui um jeito de pegar o histórico de cotações direto da B3.
